name: Run Parse

on:
  workflow_dispatch:

jobs:
  run-parse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Sync dependencies with uv
        run: uv sync

      - name: Install Ollama CLI
        run: |
          curl -fsSL https://ollama.com/download.sh | bash

      - name: Pull all-minilm:22m model
        run: ollama pull all-minilm:22m

      - name: Start Ollama server
        run: ollama serve &
        timeout-minutes: 1

      - name: Run main script
        run: uv run python main.py

      - name: Run summarization script
        run: uv run python summarize.py

      - name: Upload DuckDB artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf_data_db
          path: pdf_data.db
