name: Run Parse

on:
  workflow_dispatch:

jobs:
  run-parse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Sync dependencies with uv
        run: uv sync

      - name: Run main script
        run: uv run python main.py

      - name: Upload DuckDB artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf_data_db
          path: pdf_data.db
